import streamlit as st
import pandas as pd

st.set_page_config(page_title="AI Recommendation System", layout="wide")

sheet_id = "198vMaLQu7oF7F53t1qHZ9bB7V81x4v0CU89KPLiPbzs"
url = f"https://docs.google.com/spreadsheets/d/{sheet_id}/export?format=csv"

try:
    df = pd.read_csv(url)
except Exception as e:
    st.error(f"Error loading Google Sheet: {e}")
    st.stop()

recommendations = {

    "gifts": {
        "birthday": ["Personalized Mug", "Chocolate Hamper", "Greeting Card Set", "Customized T-shirt", "Photo Frame",
                     "Perfume Set", "Bluetooth Speaker", "Desk Lamp", "Mini Indoor Plant", "Diary & Pen Set",
                     "Wireless Charger", "Travel Pouch", "Coffee Gift Box", "Keychain", "Wallet", "Skincare Gift Box",
                     "Scented Candles", "Smart Watch", "Wall Art", "Custom Necklace"],
        "anniversary": ["Perfume Set", "Photo Frame", "Scented Candles", "Personalized Mug", "Chocolate Hamper",
                        "Couple Keychains", "Customized T-shirt", "Mini Plant", "Desk Clock", "Travel Pouch",
                        "Coffee Gift Box", "Luxury Pen Set", "Smart Watch", "Desk Lamp", "Wine Set", "Jewelry Box",
                        "Memory Book", "Candle Set", "Customized Necklace", "Wall Art"],
        "housewarming": ["Mini Indoor Plant", "Desk Lamp", "Travel Pouch", "Wall Art", "Photo Frame", "Cushion Set",
                          "Decorative Tray", "Flower Vase", "Desk Organizer", "Scented Candles", "Clock", "Pen Set",
                          "Wall Stickers", "Smart Speaker", "Desk Calendar", "Table Lamp", "Kitchen Timer", "Coaster Set",
                          "Serving Tray", "Welcome Mat"],
        "graduation": ["Personalized Mug", "Certificate Frame", "Diary Set", "Books", "Desk Organizer", "Smart Watch",
                       "Pen Set", "Laptop Sleeve", "Photo Frame", "Planner", "Coffee Gift Box", "Motivational Poster",
                       "Mini Plant", "Bluetooth Speaker", "Wallet", "Desk Lamp", "Wall Art", "Gift Card", "Headphones",
                       "Keychain"],
        "festival": ["Chocolate Hamper", "Scented Candles", "Decorative Lights", "Diyas", "Gift Box", "Torans",
                     "Flower Garlands", "Festive Cushions", "Wall Hangings", "Greeting Cards", "Puja Thali", "Incense Sticks",
                     "Decorative Plates", "Lanterns", "Traditional Lamps", "Candy Basket", "Mini Plant", "Coasters",
                     "Gift Wrap", "Candle Set"],
        "romantic": ["Rose Bouquet", "Perfume Set", "Photo Frame", "Customized Mug", "Chocolates", "Jewelry Box",
                     "Candle Set", "Couple Keychains", "Mini Plant", "Personalized T-shirt", "Smart Watch", "Travel Pouch",
                     "Desk Lamp", "Greeting Card Set", "Wall Art", "Coffee Gift Box", "Book", "Planner", "Wallet", "Necklace"],
        "thank you": ["Chocolate Box", "Personalized Mug", "Desk Organizer", "Mini Plant", "Notebook", "Pen Set",
                      "Photo Frame", "Gift Card", "Coffee Gift Box", "Keychain", "Candle Set", "Wallet", "Desk Lamp",
                      "Wall Art", "Planner", "Travel Pouch", "Bluetooth Speaker", "Scented Candles", "Flower Vase",
                      "Greeting Card Set"],
        "get well soon": ["Flower Bouquet", "Scented Candles", "Chocolate Box", "Greeting Card", "Mini Plant",
                          "Desk Lamp", "Planner", "Personalized Mug", "Photo Frame", "Notebook", "Pen Set", "Wallet",
                          "Coffee Gift Box", "Book", "Desk Organizer", "Wall Art", "Travel Pouch", "Candle Set",
                          "Smart Watch", "Keychain"],
        "baby shower": ["Baby Clothes", "Soft Toys", "Baby Blanket", "Photo Frame", "Personalized Mug", "Mini Plant",
                        "Decorative Tray", "Wall Art", "Candle Set", "Planner", "Chocolate Box", "Gift Card", "Book",
                        "Desk Lamp", "Travel Pouch", "Greeting Card", "Desk Organizer", "Keychain", "Coffee Gift Box",
                        "Wallet"],
        "corporate": ["Desk Organizer", "Planner", "Pen Set", "Notebook", "Desk Lamp", "Coffee Mug", "Photo Frame",
                      "Travel Pouch", "Gift Card", "Smart Watch", "Mini Plant", "Wall Art", "Wireless Charger",
                      "Laptop Sleeve", "Business Card Holder", "Chocolate Box", "Candle Set", "Wallet", "Desk Clock",
                      "Bluetooth Speaker"]
    },

    "clothes": {
        "party": ["Party Gown", "Blazer", "Printed Dupatta", "Formal Dress", "Cocktail Dress", "Sequined Top",
                  "Evening Saree", "Dress Shirt", "Suit Pants", "Cocktail Skirt", "Blazer Jacket", "Silk Shirt",
                  "Velvet Dress", "Shimmer Top", "Party Kurti", "Tuxedo Shirt", "Sequin Dress", "Party Jumpsuit",
                  "Formal Skirt", "Dress Shoes"],
        "casual": ["Casual T-shirt", "Jeans", "Hoodie", "Sweatshirt", "Denim Jacket", "Leggings", "Cotton Top",
                   "Casual Shirt", "Sneakers", "Tank Top", "Casual Dress", "Pullover", "Chinos", "Shorts",
                   "Joggers", "Graphic Tee", "Loose Pants", "Casual Kurti", "Cardigan", "Slip-on Shoes"],
        "formal": ["Formal Shirt", "Office Wear Set", "Kurti", "Blazer", "Formal Pants", "Pencil Skirt", "Suit Jacket",
                   "Dress Shirt", "Tie", "Blouse", "Button-down Shirt", "Dress Pants", "Formal Dress", "Waistcoat",
                   "Formal Skirt", "Blazer Dress", "Tailored Pants", "Shirt Dress", "Dress Shoes", "Office Coat"],
        "sports": ["Track Pants", "Sports T-shirt", "Gym Shorts", "Hoodie", "Leggings", "Running Shoes",
                   "Sweatband", "Sports Jacket", "Compression Shirt", "Tank Top", "Yoga Pants", "Sneakers",
                   "Sports Socks", "Jersey", "Sweatshirt", "Training Shoes", "Tracksuit", "Shorts", "Fitness Gloves",
                   "Cap"],
        "winter": ["Winter Coat", "Sweater", "Jacket", "Scarf", "Gloves", "Beanie", "Wool Socks", "Thermal Top",
                   "Parka", "Boots", "Cardigan", "Down Jacket", "Wool Sweater", "Mittens", "Poncho", "Overcoat",
                   "Leg Warmers", "Turtleneck", "Fleece Jacket", "Knit Hat"],
        "summer": ["Cotton Shirt", "T-shirt", "Shorts", "Tank Top", "Summer Dress", "Skirt", "Capri Pants",
                   "Flip Flops", "Sunglasses", "Sun Hat", "Linen Shirt", "Sleeveless Top", "Short Sleeve Dress",
                   "Sandals", "Casual Shoes", "Cotton Pants", "Light Cardigan", "Summer Jumpsuit", "Beach Dress",
                   "Espadrilles"],
        "ethnic": ["Saree", "Kurti", "Anarkali Suit", "Lehenga", "Salwar Kameez", "Dupatta", "Sherwani", "Kurta Pajama",
                   "Ethnic Jacket", "Ethnic Skirt", "Churidar", "Ethnic Top", "Designer Saree", "Embroidered Kurti",
                   "Ethnic Dress", "Silk Saree", "Banarasi Saree", "Festive Kurti", "Traditional Jacket", "Ethnic Pants"],
        "loungewear": ["Sweatshirt", "Sweatpants", "Pajama Set", "Hoodie", "Tank Top", "Shorts", "Joggers",
                       "Casual Tee", "Leggings", "Nightgown", "Lounge Pants", "Soft T-shirt", "Robe", "Tracksuit",
                       "Slippers", "Pyjama Shirt", "Comfy Shorts", "Tank Top", "Lounge Hoodie", "Sleepwear Set"],
        "formal office": ["Blazer", "Formal Shirt", "Dress Pants", "Office Wear Set", "Tie", "Blouse", "Suit Jacket",
                          "Formal Skirt", "Dress Shoes", "Waistcoat", "Shirt Dress", "Office Coat", "Pencil Skirt",
                          "Dress Shirt", "Button-down Shirt", "Blazer Dress", "Formal Dress", "Tailored Pants",
                          "Dress Shoes", "Formal Pants"],
        "swimwear": ["Bikini", "Swim Shorts", "Swimsuit", "Tankini", "Rash Guard", "Board Shorts", "One-piece Swimsuit",
                     "Cover-up Dress", "Swim Top", "Swim Bottom", "Beach Dress", "Swim Skirt", "Swim Trunks",
                     "Swim Cap", "Water Shoes", "Sun Protective Swimwear", "Kids Swimsuit", "Men’s Swim Briefs",
                     "Sports Bikini", "Ladies Swimsuit"]
    },

    "furniture": {
        "living room": ["Sofa Set", "Coffee Table", "TV Unit", "Armchair", "Bookshelf", "Side Table", "Floor Lamp",
                        "Rug", "Cushion Set", "Wall Art", "Console Table", "Pouf", "Media Cabinet", "Storage Ottoman",
                        "Book Rack", "Recliner Chair", "TV Stand", "Accent Chair", "Corner Shelf", "Plant Stand"],
        "bedroom": ["Bed", "Wardrobe", "Bedside Table", "Dresser", "Chest of Drawers", "Nightstand", "Desk",
                    "Mirror", "Wardrobe Cabinet", "Storage Bench", "Vanity Table", "Bookshelf", "Mattress",
                    "Headboard", "Side Chair", "Under-bed Storage", "Armchair", "Linen Cabinet", "Ottoman", "Lamp"],
        "dining room": ["Dining Table", "Dining Chairs", "Sideboard", "Bar Stool", "Buffet Table", "Dining Bench",
                        "Dining Set", "Hutch", "Corner Cabinet", "China Cabinet", "Serving Cart", "Bar Cabinet",
                        "Wine Rack", "Dining Table Decor", "Console Table", "Table Runner", "Chair Cushion", "Lighting",
                        "Placemat Set", "Tableware Cabinet"],
        "office": ["Office Chair", "Study Table", "Bookshelf", "File Cabinet", "Desk", "Storage Cabinet", "Credenza",
                   "Office Armchair", "Printer Stand", "Desk Organizer", "Meeting Table", "Conference Chair", "Filing Cabinet",
                   "Bookshelf Cabinet", "Drawer Unit", "Laptop Stand", "Whiteboard Stand", "Side Table", "Shelf Unit", "Corkboard"],
        "kids room": ["Bunk Bed", "Study Table", "Bookshelf", "Toy Chest", "Wardrobe", "Desk Chair", "Bean Bag",
                      "Storage Cubes", "Activity Table", "Bedside Table", "Toy Organizer", "Kids Desk", "Wall Shelf",
                      "Play Mat", "Rocking Chair", "Kids Chair", "Storage Bins", "Night Light", "Rug", "Bean Bag Chair"],
        "outdoor": ["Garden Chair", "Patio Table", "Outdoor Sofa", "Sun Lounger", "Hammock", "Bench", "Picnic Table",
                    "Outdoor Cabinet", "Swing Chair", "Planter Stand", "Outdoor Stool", "Deck Chair", "Outdoor Coffee Table",
                    "Patio Umbrella", "Bar Stool", "Outdoor Ottoman", "Gazebo", "Fire Pit Table", "Outdoor Storage Box", "Side Table"],
        "storage": ["Bookshelf", "Wardrobe", "Chest of Drawers", "Storage Cabinet", "Sideboard", "Media Cabinet", "Drawer Unit",
                    "Storage Bench", "Cupboard", "Closet Organizer", "Toy Chest", "Shoe Rack", "Filing Cabinet", "Pantry Cabinet",
                    "Storage Baskets", "Under-bed Storage", "Wall Shelves", "Closet Shelving", "Desk Organizer", "Storage Ottoman"],
        "decorative": ["Console Table", "Wall Shelf", "Coffee Table", "Accent Chair", "Side Table", "Bookshelf", "Decorative Mirror",
                       "Vase", "Wall Art", "Photo Frame", "Indoor Plant", "Floor Lamp", "Table Lamp", "Candle Holder", "Pouf",
                       "Sculpture", "Tray", "Book Rack", "Clock", "Planter Stand"],
        "office furniture": ["Desk", "Office Chair", "Bookshelf", "File Cabinet", "Meeting Table", "Conference Chair", "Credenza",
                             "Drawer Unit", "Printer Stand", "Laptop Stand", "Bookshelf Cabinet", "Whiteboard Stand", "Side Table",
                             "Filing Cabinet", "Armchair", "Desk Organizer", "Shelf Unit", "Book Rack", "Storage Cabinet", "Corkboard"],
        "multi-purpose": ["Foldable Table", "Foldable Chair", "Storage Ottoman", "Convertible Sofa", "Murphy Bed", "Drawer Unit",
                          "Bookshelf", "Desk", "Wardrobe", "Bench", "Accent Chair", "Coffee Table", "Corner Shelf", "Wall Shelf",
                          "Filing Cabinet", "Nightstand", "Console Table", "Storage Baskets", "Side Table", "TV Unit"]
    },

    # Add remaining 14 categories following the same pattern: 10 subcategories x 20 items
"home decor" : {
    "living room": ["Wall Art", "Wall Clock", "Indoor Plants", "Area Rug", "Cushion Covers", "Coffee Table Decor",
                    "Curtains", "Decorative Tray", "Photo Frames", "Floor Lamp", "Table Lamp", "Wall Shelves",
                    "Vases", "Candles", "Throw Blanket", "Accent Chairs", "Decorative Mirror", "Wall Stickers",
                    "Indoor Fountain", "Sculptures"],
    "bedroom": ["Bedside Lamp", "Wall Art", "Photo Frames", "Curtains", "Rug", "Indoor Plants", "Bedding Set",
                "Throw Blanket", "Decorative Mirror", "Cushion Covers", "Wall Clock", "Bed Canopy", "Candles",
                "Vases", "Bedside Table Decor", "Jewelry Box", "Mirror Tray", "Wall Shelf", "Hanging Decor",
                "String Lights"],
    "kitchen": ["Countertop Decor", "Wall Clock", "Indoor Plants", "Decorative Tray", "Fruit Basket", "Candle Set",
                "Kitchen Wall Art", "Vases", "Storage Jars", "Spice Rack Decor", "Table Centerpiece", "Tea Set Decor",
                "Wall Stickers", "Kitchen Clock", "Planter", "Cutting Board Decor", "Tray", "Chalkboard Sign",
                "Jar Labels", "Mug Rack"],
    "bathroom": ["Soap Dispenser", "Toothbrush Holder", "Towel Set", "Wall Art", "Indoor Plant", "Bath Mat",
                 "Mirror", "Shower Curtain", "Wall Shelves", "Candle Set", "Decorative Tray", "Storage Baskets",
                 "Hanging Hooks", "Bathrobe", "Towel Rack", "Vase", "Decorative Jars", "Wall Clock", "Tray",
                 "Scent Diffuser"],
    "outdoor": ["Garden Lantern", "Wind Chime", "Planter Stand", "Outdoor Rug", "Outdoor Cushion", "Garden Statues",
                "Outdoor Table Decor", "Bird Feeder", "Outdoor Lighting", "Patio String Lights", "Fountain",
                "Garden Planters", "Outdoor Wall Art", "Garden Flags", "Planter Box", "Garden Bench", "Umbrella",
                "Outdoor Rug", "Decorative Stones", "Plant Pots"],
    "office": ["Desk Organizer", "Wall Art", "Indoor Plant", "Desk Lamp", "Wall Clock", "File Tray", "Photo Frames",
               "Bookshelf Decor", "Pen Holder", "Bulletin Board", "Tray", "Decorative Box", "Wall Shelf", "Calendar",
               "Vases", "Candle Set", "Paperweight", "Laptop Stand Decor", "Wall Sticker", "Desk Mat"],
    "decorative accessories": ["Vases", "Candles", "Picture Frames", "Wall Art", "Indoor Plants", "Wall Shelves",
                               "Table Centerpiece", "Throw Blanket", "Sculptures", "Cushion Covers", "Decorative Bowls",
                               "Wall Clock", "Tray", "Photo Album", "Planter", "String Lights", "Decorative Boxes",
                               "Mirrors", "Wind Chimes", "Bookends"],
    "lighting": ["Floor Lamp", "Table Lamp", "Wall Sconce", "Pendant Light", "String Lights", "Chandelier",
                 "Desk Lamp", "Night Lamp", "LED Strip Light", "Candle Holder Lamp", "Wall Lantern", "Reading Lamp",
                 "Desk Light", "Bedside Lamp", "Outdoor Lantern", "Ceiling Light", "Hanging Lamp", "Fairy Lights",
                 "Accent Lamp", "Torch Lamp"],
    "textiles": ["Curtains", "Rugs", "Cushion Covers", "Throws", "Table Runner", "Bedspread", "Bedding Set",
                 "Blankets", "Napkins", "Towel Set", "Chair Covers", "Floor Mats", "Tablecloth", "Shower Curtain",
                 "Pillow Covers", "Doormats", "Kitchen Towels", "Bed Skirt", "Chair Cushion", "Wall Hangings"],
    "mirrors": ["Full-length Mirror", "Wall Mirror", "Vanity Mirror", "Decorative Mirror", "Bathroom Mirror",
                "Standing Mirror", "Tabletop Mirror", "Accent Mirror", "Round Mirror", "Oval Mirror", "LED Mirror",
                "Framed Mirror", "Mirror Tray", "Handheld Mirror", "Wardrobe Mirror", "Hanging Mirror", "Desk Mirror",
                "Decorative Wall Mirror", "Mirror Panels", "Double-sided Mirror"]
},

"electronics" : {
    "smartphones": ["iPhone 15", "Samsung Galaxy S23", "Google Pixel 8", "OnePlus 11", "Xiaomi 13",
                    "Realme GT", "Samsung A54", "Oppo Reno 10", "Vivo V29", "Motorola Edge", "iPhone SE",
                    "Samsung M53", "Google Pixel 7a", "OnePlus Nord", "Redmi Note 12", "Asus Zenfone", "Sony Xperia",
                    "Nokia X20", "Huawei P50", "Tecno Camon"],
    "laptops": ["MacBook Air", "MacBook Pro", "Dell XPS 13", "HP Spectre x360", "Lenovo ThinkPad X1",
                "Asus ZenBook", "Acer Swift", "MSI Modern", "Razer Blade", "Surface Laptop 5",
                "Dell Inspiron", "HP Envy", "Lenovo Yoga", "Asus Vivobook", "Acer Predator", "MSI GF66",
                "LG Gram", "Samsung Galaxy Book", "Huawei MateBook", "Toshiba Satellite"],
    "tablets": ["iPad Pro", "iPad Air", "Samsung Galaxy Tab S8", "Lenovo Tab P11", "Huawei MatePad",
                "Microsoft Surface Go", "Amazon Fire HD 10", "Samsung Galaxy Tab A8", "Xiaomi Pad 5", "Realme Pad",
                "Lenovo Tab M10", "Huawei MatePad T10", "Apple iPad Mini", "Asus ZenPad", "Chuwi HiPad", "Microsoft Surface Pro",
                "Samsung Galaxy Tab S7", "Alldocube iPlay", "Amazon Fire 7", "Lenovo Tab P12"],
    "smartwatches": ["Apple Watch Series 9", "Samsung Galaxy Watch 6", "Fitbit Versa 4", "Garmin Venu 2",
                     "Fossil Gen 6", "Amazfit GTR 4", "Huawei Watch GT3", "Realme Watch 3", "TicWatch Pro 3",
                     "Samsung Galaxy Watch 5", "Garmin Fenix 7", "Fitbit Sense 2", "Apple Watch SE", "Suunto 9",
                     "Honor Watch GS3", "Withings ScanWatch", "Polar Ignite 3", "Mobvoi TicWatch E3", "Garmin Vivoactive 4",
                     "Huawei Watch Fit 2"],
    "headphones": ["Sony WH-1000XM5", "Bose QuietComfort 45", "Apple AirPods Pro 2", "Samsung Galaxy Buds 3",
                   "JBL Live 660NC", "Sennheiser HD 450BT", "Beats Studio 3", "Anker Soundcore Life Q35",
                   "Sony WF-1000XM4", "Bose Sport Earbuds", "OnePlus Buds Pro", "Marshall Major IV", "Skullcandy Crusher",
                   "Bang & Olufsen Beoplay H9", "Jabra Elite 85t", "Sony MDR-XB950", "Bose QuietComfort Earbuds", "Philips Fidelio L3",
                   "Plantronics BackBeat Pro 2", "Shure AONIC 50"],
    "televisions": ["Samsung QLED 8K", "LG OLED C2", "Sony Bravia X90K", "TCL 6-Series", "Samsung Neo QLED",
                    "LG NanoCell", "Sony X85K", "Panasonic JZ2000", "Philips OLED806", "Hisense U8H", "Samsung TU8000",
                    "LG C1 OLED", "Sony A90J OLED", "TCL 5-Series", "Vizio M-Series", "Panasonic GX800", "Sony X95J",
                    "LG G2 OLED", "Samsung Q70B", "Philips 8606"],
    "cameras": ["Canon EOS R6", "Nikon Z6 II", "Sony A7 IV", "Fujifilm X-T4", "Panasonic Lumix GH5",
                "Canon EOS 90D", "Nikon D7500", "Sony A6400", "Canon M50 Mark II", "Olympus OM-D E-M10",
                "Fujifilm X-S10", "Leica Q2", "Sony RX100 VII", "Panasonic Lumix S5", "Canon EOS RP", "Nikon Z50",
                "Pentax K-70", "GoPro HERO11", "DJI Pocket 2", "Canon PowerShot G7 X"],
    "gaming": ["PlayStation 5", "Xbox Series X", "Nintendo Switch OLED", "Steam Deck", "PS5 Digital Edition",
               "Xbox Series S", "Nintendo Switch Lite", "PS4 Pro", "Xbox One X", "Gaming Laptop Dell G15",
               "Gaming Laptop ASUS ROG", "Gaming Laptop MSI", "Gaming Chair DXRacer", "Logitech G Pro Mouse", "Razer Huntsman Keyboard",
               "Corsair K70 Keyboard", "Sony Pulse 3D Headset", "Alienware Monitor 27", "HP Omen Monitor 24", "Elgato Stream Deck"],
    "accessories": ["Phone Case", "Screen Protector", "Laptop Sleeve", "Mouse Pad", "Keyboard Cover", "USB Hub",
                    "External Hard Drive", "Power Bank", "Charging Cable", "Docking Station", "Headphone Stand",
                    "Tripod", "Camera Bag", "Memory Card", "Laptop Stand", "Smartwatch Strap", "VR Headset", "Stylus Pen",
                    "Selfie Stick", "Cable Organizer"],
    "home appliances": ["Refrigerator", "Washing Machine", "Microwave Oven", "Air Conditioner", "Vacuum Cleaner",
                        "Dishwasher", "Water Purifier", "Induction Cooktop", "Air Fryer", "Coffee Maker",
                        "Blender", "Toaster", "Electric Kettle", "Rice Cooker", "Juicer", "Mixer Grinder",
                        "Iron", "Hair Dryer", "Fan", "Heater"]
},
 "kitchen essentials" : {
    "cookware": ["Non-stick Pan", "Saucepan", "Frying Pan", "Pressure Cooker", "Dutch Oven", "Cast Iron Skillet",
                 "Grill Pan", "Casserole Dish", "Wok", "Stockpot", "Baking Dish", "Roasting Pan", "Paella Pan",
                 "Steamer", "Soup Pot", "Crepe Pan", "Sauté Pan", "Tamis", "Braiser", "Double Boiler"],
    "utensils": ["Spatula", "Ladle", "Tongs", "Whisk", "Peeler", "Garlic Press", "Grater", "Measuring Cups",
                 "Measuring Spoons", "Slotted Spoon", "Knife Set", "Chopping Board", "Pastry Brush", "Sieve",
                 "Ice Cream Scoop", "Pizza Cutter", "Mandoline", "Rolling Pin", "Kitchen Shears", "Citrus Juicer"],
    "appliances": ["Mixer Grinder", "Electric Kettle", "Air Fryer", "Toaster", "Blender", "Coffee Maker",
                   "Microwave", "Juicer", "Rice Cooker", "Food Processor", "Hand Mixer", "Electric Grill",
                   "Sandwich Maker", "Slow Cooker", "Popcorn Maker", "Electric Griddle", "Ice Cream Maker",
                   "Pressure Cooker (Electric)", "Yogurt Maker", "Electric Chopper"],
    "storage": ["Food Containers", "Glass Jars", "Spice Rack", "Bread Box", "Canisters", "Lunch Boxes",
                "Snack Boxes", "Jar Set", "Airtight Containers", "Basket Set", "Water Bottles", "Cookie Jar",
                "Egg Storage", "Wine Rack", "Condiment Dispenser", "Pot Rack", "Pan Organizer", "Kitchen Caddy",
                "Stackable Containers", "Cabinet Organizer"],
    "cutlery": ["Knife Set", "Forks", "Spoons", "Serving Spoons", "Salad Tongs", "Steak Knives", "Soup Spoons",
                "Dessert Forks", "Chopsticks", "Butter Knife", "Serving Fork", "Cake Server", "Ice Cream Spoon",
                "Ladle", "Pastry Knife", "Fruit Knife", "Cheese Knife", "Spaghetti Server", "Sugar Tongs", "Tea Spoon"],
    "baking": ["Baking Tray", "Muffin Pan", "Cake Pan", "Rolling Pin", "Measuring Cups", "Whisk", "Mixing Bowls",
               "Cooling Rack", "Silicone Mat", "Pastry Brush", "Cookie Cutter", "Cake Tester", "Icing Spatula",
               "Dough Scraper", "Pie Dish", "Bread Loaf Pan", "Cupcake Liners", "Fondant Tools", "Baking Scale", "Tart Pan"],
    "beverages": ["Coffee Maker", "French Press", "Electric Kettle", "Tea Infuser", "Juicer", "Blender",
                  "Cocktail Shaker", "Mason Jar", "Smoothie Blender", "Water Filter Pitcher", "Milk Frother",
                  "Ice Cube Tray", "Coffee Grinder", "Tea Kettle", "Electric Mixer", "Soda Maker", "Bottle Opener",
                  "Wine Opener", "Measuring Pitcher", "Tumbler Set"],
    "cleaning": ["Dish Soap", "Scrub Brush", "Dish Rack", "Sponge Set", "Cleaning Cloth", "Dish Gloves", "Steel Wool",
                 "Broom", "Dustpan", "Mop", "Trash Bin", "Trash Bags", "Counter Cleaner", "Spray Bottle", "Scouring Pad",
                 "Microfiber Cloth", "Sink Caddy", "Garbage Disposal Brush", "Scraper", "Odor Neutralizer"],
    "knives": ["Chef Knife", "Paring Knife", "Bread Knife", "Santoku Knife", "Carving Knife", "Utility Knife",
               "Boning Knife", "Cleaver", "Fillet Knife", "Steak Knife", "Nakiri Knife", "Tomato Knife", "Peeling Knife",
               "Sushi Knife", "Butter Knife", "Kitchen Scissors", "Knife Sharpener", "Ceramic Knife", "Fruit Knife",
               "Salmon Knife"],
    "miscellaneous": ["Kitchen Timer", "Thermometer", "Measuring Scale", "Bottle Opener", "Corkscrew", "Grater",
                      "Can Opener", "Ice Cream Scoop", "Mandoline", "Strainer", "Rolling Pin", "Cooking Torch",
                      "Salad Spinner", "Egg Separator", "Pot Holders", "Trivet", "Colander", "Pastry Mat", "Chopping Board",
                      "Oil Dispenser"]
},
  "study essentials" : {
    "stationery": ["Notebooks", "Pens", "Pencils", "Markers", "Highlighters", "Erasers", "Sharpener", "Ruler",
                   "Sticky Notes", "Index Cards", "Stapler", "Paper Clips", "Binder Clips", "Scissors", "Glue Stick",
                   "Correction Tape", "File Folders", "Notebook Set", "Graph Paper", "Journal"],
    "desk setup": ["Study Table", "Ergonomic Chair", "Table Lamp", "Desk Organizer", "Cork Board", "Desk Mat",
                   "Laptop Stand", "Cable Organizer", "Pen Holder", "Whiteboard", "Desk Shelf", "Monitor Stand",
                   "Desk Drawer", "Stationery Caddy", "Keyboard Tray", "Mouse Pad", "Foot Rest", "Desk Clock",
                   "Desk Lamp with USB", "Magazine Rack"],
    "gadgets": ["Laptop", "Tablet", "Headphones", "Calculator", "Printer", "External Hard Drive", "USB Drive",
                "Mouse", "Keyboard", "Smartwatch", "Scanner", "Webcam", "Router", "Projector", "Portable Charger",
                "Tablet Stylus", "Bluetooth Speaker", "Laser Pointer", "Microphone", "Drawing Tablet"],
    "books": ["Academic Textbooks", "Reference Books", "Novels", "Self-help Books", "Poetry Collections",
              "Biographies", "Comics", "Science Books", "Technology Books", "History Books", "Language Books",
              "Exam Preparation Guides", "Motivational Books", "Finance Books", "Business Books", "Travel Books",
              "Children’s Books", "Art Books", "Photography Books", "Engineering Books"],
    "organization": ["File Folders", "Binders", "Magazine Holders", "Label Stickers", "Document Organizer",
                     "Drawer Organizers", "Bookends", "Stackable Trays", "Pen Holder", "Whiteboard Organizer",
                     "Sticky Notes Set", "Index Dividers", "Cable Clips", "Storage Boxes", "Desk Drawer Divider",
                     "Clipboard", "Hanging File", "Plastic Envelope", "Magazine Rack", "Planner Organizer"],
    "lighting": ["LED Desk Lamp", "Adjustable Lamp", "Table Lamp", "Clip Lamp", "Floor Lamp", "Task Light",
                 "Smart Lamp", "Night Light", "Portable Lamp", "Lamp with USB", "Dimmable Lamp", "Lamp with Magnifier",
                 "Study Lamp", "Battery Operated Lamp", "LED Strip Light", "Clamp Lamp", "LED Reading Light",
                 "Desk Spotlight", "Rechargeable Lamp", "Desk Light with Timer"],
    "backpacks": ["Laptop Backpack", "School Bag", "Messenger Bag", "College Backpack", "Travel Backpack", "Roll-top Bag",
                  "Canvas Backpack", "Drawstring Bag", "Tote Bag", "Sling Bag", "Hiking Backpack", "Mini Backpack",
                  "Leather Backpack", "Waterproof Backpack", "Sports Backpack", "Expandable Backpack", "Anti-theft Bag",
                  "Student Backpack", "Organizer Backpack", "Tablet Backpack"],
    "writing tools": ["Fountain Pen", "Ballpoint Pen", "Gel Pen", "Mechanical Pencil", "Regular Pencil", "Marker",
                      "Highlighter", "Calligraphy Pen", "Brush Pen", "Fineliner", "Permanent Marker", "Whiteboard Marker",
                      "Erasable Pen", "Colored Pencil", "Chalk Pen", "Crayons", "Pastel Pencils", "Sharpener",
                      "Pen Refill", "Ink Bottle"],
    "calculators": ["Scientific Calculator", "Graphing Calculator", "Basic Calculator", "Financial Calculator",
                    "Printing Calculator", "Programmable Calculator", "Solar Calculator", "Desktop Calculator",
                    "Handheld Calculator", "Statistics Calculator", "Engineering Calculator", "Fraction Calculator",
                    "Currency Calculator", "Scientific Calculator with Solar", "Casio FX Series", "Texas Instruments TI-84",
                    "Sharp EL Series", "Canon Calculator", "HP 12C Financial", "Calculator Cover"],
    "miscellaneous": ["Sticky Notes", "Index Cards", "Bookmarks", "Clipboard", "Paper Clips", "Binder Clips", "Rubber Bands",
                      "Magnifying Glass", "Desk Calendar", "Timer", "Whiteboard", "Pin Board", "Compass", "Protractor",
                      "Calculator Case", "Pencil Box", "Pen Stand", "Label Maker", "Book Cover", "Document Sleeve"]
},
    # Books
"books" : {

    "comedy": [
        "Diary of a Wimpy Kid", "Good Omens", "Bossypants", "Catch-22",
        "The Hitchhiker’s Guide to the Galaxy", "Bridget Jones’s Diary",
        "Me Talk Pretty One Day", "Yes Please", "Is Everyone Hanging Out Without Me?",
        "The Rosie Project", "Hyperbole and a Half", "Three Men in a Boat",
        "Confessions of a Shopaholic", "The Importance of Being Earnest",
        "The Princess Bride", "A Man Called Ove", "The Code of the Woosters",
        "The 100-Year-Old Man Who Climbed Out the Window",
        "Bossypants", "Life, the Universe and Everything"
    ],

    "romance": [
        "Pride and Prejudice", "Me Before You", "The Notebook", "Outlander",
        "The Fault in Our Stars", "Love, Rosie", "It Ends With Us",
        "November 9", "Eleanor & Park", "Anna and the French Kiss",
        "The Time Traveler’s Wife", "Twilight", "The Hating Game",
        "Red, White & Royal Blue", "The Lucky One", "One Day",
        "The Rosie Effect", "Call Me By Your Name", "Normal People",
        "Five Feet Apart"
    ],

    "thriller": [
        "Gone Girl", "The Girl on the Train", "The Silent Patient", "Shutter Island",
        "Before I Go to Sleep", "The Da Vinci Code", "Angels & Demons",
        "The Woman in the Window", "The Couple Next Door",
        "Dark Places", "The Reversal", "The Firm", "The Client",
        "Behind Closed Doors", "Final Girls", "The Last Mrs. Parrish",
        "Lock Every Door", "Before She Knew Him",
        "The Last Time I Lied", "Sharp Objects"
    ],

    "horror": [
        "The Shining", "It", "Dracula", "Frankenstein",
        "The Haunting of Hill House", "Bird Box", "Pet Sematary",
        "The Exorcist", "World War Z", "The Girl with All the Gifts",
        "House of Leaves", "Coraline", "The Turn of the Screw",
        "The Silence of the Lambs", "Mexican Gothic",
        "The Call of Cthulhu", "Carrie", "The Stand",
        "Salem’s Lot", "The Woman in Black"
    ],

    "science fiction": [
        "Dune", "Ender’s Game", "Foundation", "Neuromancer",
        "The Martian", "Snow Crash", "1984", "Brave New World",
        "Fahrenheit 451", "Ready Player One", "The War of the Worlds",
        "The Time Machine", "Do Androids Dream of Electric Sheep?",
        "The Hitchhiker’s Guide to the Galaxy",
        "Project Hail Mary", "The Left Hand of Darkness",
        "Hyperion", "The Forever War",
        "Old Man’s War", "The Three-Body Problem"
    ],

    "self-help": [
        "Atomic Habits", "The 7 Habits of Highly Effective People",
        "How to Win Friends and Influence People", "Think and Grow Rich",
        "The Power of Habit", "You Are a Badass",
        "The Subtle Art of Not Giving a F*ck", "Mindset",
        "Deep Work", "The Four Agreements",
        "The Miracle Morning", "Grit",
        "Essentialism", "Drive", "The Confidence Code",
        "Eat That Frog", "Make Your Bed",
        "The One Thing", "Tools of Titans",
        "Ikigai"
    ],

    "biography": [
        "Steve Jobs", "Becoming", "Educated",
        "The Diary of a Young Girl", "Long Walk to Freedom",
        "Elon Musk", "Born a Crime", "Open",
        "Unbroken", "Shoe Dog",
        "Wings of Fire", "Playing It My Way",
        "My Experiments with Truth", "Einstein: His Life and Universe",
        "Churchill: A Life", "Alexander Hamilton",
        "Leonardo da Vinci", "The Wright Brothers",
        "Bossypants", "Into the Wild"
    ],

    "fantasy": [
        "Harry Potter Series", "The Lord of the Rings",
        "The Hobbit", "Percy Jackson Series",
        "A Song of Ice and Fire", "The Chronicles of Narnia",
        "The Name of the Wind", "Mistborn",
        "The Wheel of Time", "Eragon",
        "The Magicians", "Shadow and Bone",
        "The Witcher", "Good Omens",
        "The Night Circus", "The Dark Tower",
        "His Dark Materials", "American Gods",
        "The Silmarillion", "The Priory of the Orange Tree"
    ],

    "children": [
        "Harry Potter", "Charlie and the Chocolate Factory",
        "Matilda", "The Jungle Book", "The Gruffalo",
        "Winnie-the-Pooh", "Peter Pan", "The Cat in the Hat",
        "Charlotte’s Web", "Alice in Wonderland",
        "The Secret Garden", "The Little Prince",
        "Paddington Bear", "The Chronicles of Narnia",
        "Diary of a Wimpy Kid", "Percy Jackson",
        "The Magic Tree House", "The BFG",
        "Stuart Little", "The Very Hungry Caterpillar"
    ],

    "academic & career": [
        "Cracking the Coding Interview", "Introduction to Algorithms",
        "Clean Code", "Design Patterns",
        "Artificial Intelligence: A Modern Approach",
        "Operating System Concepts", "Database System Concepts",
        "Computer Networks", "Python Crash Course",
        "Head First Java", "Let Us C",
        "Structure and Interpretation of Computer Programs",
        "Deep Learning", "Data Science from Scratch",
        "The Pragmatic Programmer", "Code Complete",
        "Algorithms Unlocked", "Machine Learning Yearning",
        "Hands-On Machine Learning", "System Design Interview"
    ]
},


  "movies" : {
    "action": ["Avengers: Endgame", "John Wick", "Mad Max: Fury Road", "The Dark Knight", "Gladiator",
               "Die Hard", "Mission Impossible", "The Matrix", "Inception", "Fast & Furious 9", "Wonder Woman",
               "Black Panther", "Spider-Man: No Way Home", "Captain America: Civil War", "Iron Man",
               "Thor: Ragnarok", "Guardians of the Galaxy", "Logan", "Casino Royale", "The Bourne Identity"],
    "comedy": ["The Hangover", "Superbad", "Step Brothers", "Bridesmaids", "Anchorman", "The 40-Year-Old Virgin",
               "Pitch Perfect", "Crazy Rich Asians", "Dumb and Dumber", "Zoolander", "Ted", "21 Jump Street",
               "Coming to America", "Jumanji: Welcome to the Jungle", "Horrible Bosses", "Hairspray", "Napoleon Dynamite",
               "Deadpool", "Knives Out", "Juno"],
    "romantic": ["The Notebook", "Pride and Prejudice", "Titanic", "Me Before You", "Love Actually", "La La Land",
                 "A Walk to Remember", "Twilight", "The Fault in Our Stars", "Dear John", "Notting Hill",
                 "The Vow", "Silver Linings Playbook", "Crazy Rich Asians", "Call Me by Your Name", "About Time",
                 "50 First Dates", "Ever After", "Safe Haven", "The Time Traveler's Wife"],
    "thriller": ["Gone Girl", "Se7en", "Shutter Island", "The Girl with the Dragon Tattoo", "Prisoners", "Zodiac",
                 "The Silence of the Lambs", "Memento", "Fight Club", "Black Swan", "The Sixth Sense", "Oldboy",
                 "Nightcrawler", "No Country for Old Men", "The Invisible Man", "Split", "The Prestige", "Rear Window",
                 "The Others", "A Quiet Place"],
    "horror": ["The Conjuring", "It", "Hereditary", "A Nightmare on Elm Street", "The Exorcist", "Insidious",
               "Halloween", "Paranormal Activity", "The Ring", "Annabelle", "Scream", "Saw", "The Shining", "The Babadook",
               "Sinister", "Midsommar", "Get Out", "The Blair Witch Project", "It Follows", "Candyman"],
    "animation": ["Toy Story", "Finding Nemo", "Shrek", "Frozen", "Moana", "The Lion King", "Zootopia",
                  "Coco", "Inside Out", "Ratatouille", "Despicable Me", "Minions", "Kung Fu Panda", "Tangled",
                  "The Incredibles", "Monsters Inc.", "How to Train Your Dragon", "Big Hero 6", "Cars", "Pocahontas"],
    "sci-fi": ["Interstellar", "Inception", "Blade Runner 2049", "The Matrix", "Star Wars: The Force Awakens",
               "Arrival", "Guardians of the Galaxy", "Avatar", "Jurassic Park", "Terminator 2", "Minority Report",
               "The Fifth Element", "E.T.", "Rogue One", "Edge of Tomorrow", "District 9", "Ex Machina", "Dune",
               "Ready Player One", "Star Trek"],
    "fantasy": ["Harry Potter and the Sorcerer's Stone", "The Lord of the Rings: The Fellowship of the Ring",
                "The Hobbit", "Pan's Labyrinth", "The Chronicles of Narnia", "The Princess Bride", "Stardust",
                "Percy Jackson & the Olympians", "Fantastic Beasts", "Eragon", "The Golden Compass", "Spirited Away",
                "Howl's Moving Castle", "The NeverEnding Story", "The Dark Crystal", "Coraline", "The Last Unicorn",
                "The Secret of NIMH", "Alice in Wonderland", "Ella Enchanted"],
    "documentary": ["Planet Earth", "The Last Dance", "Our Planet", "Free Solo", "Blackfish", "Icarus", "13th",
                    "Making a Murderer", "The Social Dilemma", "Inside Job", "Won’t You Be My Neighbor?", "Jiro Dreams of Sushi",
                    "The Cove", "The Game Changers", "Cosmos", "March of the Penguins", "The Fog of War", "American Factory",
                    "He Named Me Malala", "Life"],
    "musical": ["La La Land", "The Greatest Showman", "Mamma Mia!", "Les Misérables", "Chicago", "Grease", "West Side Story",
                "Beauty and the Beast", "Singin’ in the Rain", "Mary Poppins", "The Sound of Music", "Hairspray", "Rent",
                "Annie", "The Phantom of the Opera", "Evita", "Rock of Ages", "Nine", "Into the Woods", "Dreamgirls"]
},
 "beauty & skincare" : {
    "face care": ["Face Wash", "Moisturizer", "Sunscreen", "Face Serum", "Face Mask", "Exfoliator", "Toner",
                  "Face Oil", "BB Cream", "CC Cream", "Primer", "Night Cream", "Eye Cream", "Sheet Mask",
                  "Clay Mask", "Hydrating Mist", "Cleansing Oil", "Face Mist", "Makeup Remover", "Lip Balm"],
    "makeup": ["Foundation", "Concealer", "Blush", "Highlighter", "Bronzer", "Lipstick", "Lip Gloss", "Lip Liner",
               "Mascara", "Eyeliner", "Eyeshadow Palette", "Compact Powder", "Loose Powder", "Setting Spray",
               "Makeup Brushes", "Beauty Blender", "Contour Kit", "Primer", "Face Powder", "Brow Pencil"],
    "hair care": ["Shampoo", "Conditioner", "Hair Serum", "Hair Oil", "Hair Mask", "Hair Spray", "Hair Gel",
                  "Heat Protectant Spray", "Dry Shampoo", "Leave-in Conditioner", "Hair Brush", "Comb", "Hair Clips",
                  "Hair Bands", "Hair Ties", "Curling Iron", "Straightener", "Hair Rollers", "Hair Color", "Hair Dryer"],
    "body care": ["Body Lotion", "Body Scrub", "Body Wash", "Hand Cream", "Foot Cream", "Body Butter", "Shower Gel",
                  "Soap Bar", "Hand Sanitizer", "Exfoliating Gloves", "Massage Oil", "Deodorant", "Perfume",
                  "Body Mist", "Sunscreen Lotion", "After Sun Gel", "Body Mist Spray", "Bath Salt", "Bath Bomb",
                  "Loofah"],
    "tools": ["Makeup Brushes", "Beauty Blender", "Tweezers", "Eyelash Curler", "Facial Roller", "Scissors",
              "Nail Clippers", "Cuticle Pusher", "Comedone Extractor", "Hair Brush", "Comb", "Mirror", "Face Brush",
              "Makeup Organizer", "Makeup Bag", "Brush Cleaner", "Eyelash Applicator", "Blush Brush", "Brow Brush",
              "Spatula"],
    "fragrance": ["Perfume", "Body Mist", "Eau de Toilette", "Eau de Parfum", "Roll-on Perfume", "Attar",
                  "Scented Body Spray", "Room Spray", "Hair Perfume", "Solid Perfume", "Essential Oil Perfume",
                  "Fragrance Oil", "Hand Cream Scented", "Body Lotion Fragrance", "Scented Candle", "Incense Stick",
                  "Deodorant Spray", "Perfume Gift Set", "Luxury Perfume", "Travel Perfume"],
    "nails": ["Nail Polish", "Nail File", "Nail Clippers", "Cuticle Pusher", "Nail Buffer", "Nail Art Stickers",
              "Nail Art Pens", "Top Coat", "Base Coat", "Nail Glue", "Nail Polish Remover", "Acrylic Powder",
              "UV Gel", "Nail Lamp", "Nail Brush", "Nail Stickers", "Nail Gems", "Nail Rhinestones", "Nail Stencils",
              "Pedicure Set"],
    "spa & wellness": ["Body Oil", "Massage Oil", "Bath Bomb", "Bath Salt", "Face Roller", "Foot Spa Kit",
                        "Aromatherapy Oil", "Essential Oils", "Face Steamer", "Body Scrub", "Exfoliating Gloves",
                        "Shower Gel", "Hand Cream", "Foot Cream", "Body Butter", "Relaxing Candle", "Spa Kit",
                        "Herbal Oil", "Yoga Mat", "Meditation Cushion"],
    "men care": ["Face Wash", "Moisturizer", "Beard Oil", "Shaving Cream", "Aftershave", "Hair Gel", "Deodorant",
                 "Shampoo", "Conditioner", "Face Scrub", "Body Wash", "Perfume", "Nail Clippers", "Hand Cream",
                 "Sunscreen", "Lip Balm", "Hair Wax", "Beard Comb", "Hair Clay", "Face Mask"],
    "kits & sets": ["Makeup Kit", "Skincare Set", "Hair Care Kit", "Spa Kit", "Body Care Set", "Perfume Set",
                    "Nail Kit", "Travel Kit", "Men Grooming Kit", "Face Mask Set", "Blush Kit", "Lipstick Set",
                    "Eyeshadow Palette Set", "Essential Oils Set", "Bath Gift Set", "Hair Styling Kit", "Cosmetic Bag Set",
                    "Luxury Skincare Set", "Fragrance Set", "Beauty Gift Box"]
},
    "office supplies" : {
    "writing tools": ["Pens", "Pencils", "Markers", "Highlighters", "Permanent Markers", "Gel Pens", "Fountain Pen",
                      "Mechanical Pencil", "Colored Pencils", "Whiteboard Markers", "Erasers", "Correction Tape",
                      "Sharpener", "Calligraphy Pen", "Brush Pen", "Fineliners", "Sticky Notes Pen Set", "Ink Bottle",
                      "Pen Refills", "Chalk Pen"],
    "paper products": ["Notebooks", "Sticky Notes", "Printing Paper", "Graph Paper", "Index Cards", "Letter Pads",
                       "Legal Pads", "Envelopes", "File Folders", "Binders", "Notepads", "Colored Paper", "Tracing Paper",
                       "Sketch Pads", "Receipt Books", "Cardstock", "Postcards", "Memo Pads", "Planner", "Ledger Book"],
    "desk organizers": ["Desk Tray", "Pen Holder", "File Organizer", "Drawer Organizer", "Magazine Holder",
                        "Cable Organizer", "Letter Tray", "Desktop File Rack", "Stationery Caddy", "Desktop Shelf",
                        "Document Organizer", "Storage Box", "Desktop Drawer", "Sticky Note Holder", "Desk Mat",
                        "Paper Clip Holder", "Business Card Holder", "Desktop Shelf Unit", "Desktop Organizer Set",
                        "File Sorter"],
    "furniture": ["Office Chair", "Office Desk", "Filing Cabinet", "Bookshelf", "Storage Cabinet", "Conference Table",
                  "Reception Desk", "Workstation Partition", "Printer Stand", "Drawer Unit", "Laptop Table",
                  "Filing Rack", "Side Table", "Conference Chair", "Visitor Chair", "Storage Shelf", "Corner Desk",
                  "Mobile Pedestal", "Bench Seating", "Cubicle Desk"],
    "gadgets": ["Printer", "Scanner", "Calculator", "Projector", "Shredder", "Laptop", "Desktop Computer",
                "Monitor", "Keyboard", "Mouse", "Webcam", "External Hard Drive", "UPS", "Router", "Tablet",
                "Smartphone", "Fax Machine", "Label Printer", "Digital Clock", "Speakerphone"],
    "presentation": ["Whiteboard", "Projector Screen", "Flip Chart", "Marker Set", "Laser Pointer", "Notice Board",
                     "Pin Board", "Presentation Pointer", "Clicker", "Screen Cleaner", "Projector Remote",
                     "Magnetic Board", "Easel Stand", "Display Board", "Portable Whiteboard", "Projection Lamp",
                     "Presentation Kit", "Pointer Stick", "Projection Screen Stand", "Presentation Binder"],
    "stationery sets": ["Pen Set", "Pencil Set", "Marker Set", "Highlighter Set", "Desk Organizer Set", "Notebook Set",
                        "Sticky Notes Set", "Binder Clips", "Paper Clips", "Stapler Set", "Scissors Set", "Ruler Set",
                        "Correction Tape Set", "Ink Pen Set", "Desk Accessories Kit", "Label Maker Set", "Stamp Set",
                        "Envelope Set", "File Folder Set", "Punch Set"],
    "mailing & shipping": ["Envelope", "Mailing Tape", "Bubble Wrap", "Packing Paper", "Shipping Labels", "Parcel Box",
                            "Mailing Tube", "Address Labels", "Stretch Wrap", "Packing Peanuts", "Mailer Bags",
                            "Label Printer", "Document Envelope", "Shipping Scale", "Courier Envelope", "Foam Wrap",
                            "Sealing Machine", "Postal Pouch", "Adhesive Labels", "Packaging Tape Dispenser"],
    "technology accessories": ["Mouse Pad", "Keyboard Cover", "USB Hub", "Cable Organizer", "Laptop Stand", "Docking Station",
                               "HDMI Cable", "Ethernet Cable", "Webcam Cover", "Headphones", "Charger", "Power Strip",
                               "Adapter", "Extension Cord", "Laptop Cooling Pad", "Mouse", "Keyboard", "Speaker", "Monitor Stand",
                               "External Storage"],
    "miscellaneous": ["Stapler", "Punch Machine", "Clipboard", "Rubber Bands", "Thumbtacks", "Whiteboard Eraser",
                      "Tape Dispenser", "Calculator", "Label Maker", "Desk Lamp", "File Rack", "Magazine Rack", "Business Card Holder",
                      "Desk Clock", "Paper Weight", "Post-It Notes", "Envelope Opener", "Magnifying Glass", "Staple Remover", "Desk Calendar"]
},
    "festival items" : {
    "decorations": ["Fairy Lights", "Lanterns", "Rangoli Colors", "Torans", "Festive Curtains", "Wall Hangings",
                    "Flower Garlands", "String Lights", "Decorative Plates", "Candles", "Diyas", "Artificial Flowers",
                    "Festive Banners", "Festive Balloons", "Pooja Thali Decor", "Door Hangings", "Ceiling Hangings",
                    "Festive Table Cloths", "Wall Stickers", "Festive Centerpieces"],
    "puja essentials": ["Puja Thali", "Incense Sticks", "Diyas", "Bell", "Camphor", "Kumkum", "Rice", "Flower Petals",
                        "Chowki", "Pooja Mat", "Havan Samagri", "Silver Plate", "Holy Water Container", "Pooja Stand",
                        "Diya Stand", "Pooja Spoon", "Kalash", "Aarti Plate", "Conch Shell", "Chowki Cover"],
    "gifts": ["Gift Hamper", "Chocolates", "Sweets Box", "Dry Fruits", "Personalized Mug", "Perfume Set", "Keychain",
              "Wallet", "Saree", "Kurti", "Home Decor Gift", "Photo Frame", "Candle Set", "Desk Organizer", "Smart Watch",
              "Bluetooth Speaker", "Stationery Set", "Skincare Set", "Chocolate Box", "Custom T-shirt"],
    "lights": ["String Lights", "LED Candles", "Lanterns", "Fairy Lights", "Lamp Posts", "Table Lamps", "Wall Lamps",
               "Decorative Bulbs", "Festive Lanterns", "Floating Lamps", "Solar Lights", "Hanging Lamps", "LED Garland",
               "Paper Lanterns", "Diya Lights", "Battery Operated Candles", "Tea Light Candles", "Projection Lights",
               "LED Candles Set", "Festive Candle Holders"],
    "sweets & treats": ["Chocolate Box", "Dry Fruits", "Indian Sweets", "Baklava", "Laddoos", "Kaju Katli", "Barfi",
                        "Gulab Jamun", "Halwa", "Mithai Box", "Assorted Cookies", "Cupcakes", "Brownies", "Choco Bars",
                        "Toffee Box", "Fudge", "Caramel Box", "Candy Box", "Marzipan", "Festive Sweet Pack"],
    "puja accessories": ["Kalash", "Pooja Spoon", "Chowki", "Pooja Mat", "Aarti Plate", "Incense Holder", "Bell",
                         "Camphor Holder", "Silver Plate", "Holy Water Container", "Havan Samagri Box", "Diya Stand",
                         "Pooja Stand", "Pooja Thali Cover", "Flower Tray", "Chowki Cover", "Incense Stick Holder",
                         "Conch Shell", "Pooja Bell Set", "Havan Kund"],
    "clothing & attire": ["Kurti", "Saree", "Salwar Suit", "Lehenga", "Sherwani", "Kurta Pajama", "Dupatta", "Stole",
                          "Choli", "Dress Shirt", "Formal Pants", "Skirt", "Blouse", "Party Gown", "Men Ethnic Set",
                          "Women Ethnic Set", "Jacket", "Shawl", "Kurta Set", "Saree Blouse"],
    "kids festival items": ["Toy Gifts", "Sweets", "Festive Clothing", "Story Books", "Coloring Books", "Puzzle Games",
                            "School Bags", "Water Bottles", "Educational Toys", "Crayons", "Drawing Boards", "Activity Kits",
                            "Soft Toys", "Mini Games", "Festive Stickers", "Musical Toys", "Kids Watches", "Play Mats",
                            "Balloon Packs", "Party Hats"],
    "decorative items": ["Wall Hangings", "Flower Vases", "Table Centerpiece", "Decorative Candles", "Photo Frames",
                         "Festive Garland", "Table Cloths", "Door Hangings", "Ceiling Hangings", "Paper Lanterns",
                         "Hanging Ornaments", "Festive Cushions", "Decorative Bowls", "Showpieces", "Mini Statues",
                         "Wall Stickers", "Wind Chimes", "Candlesticks", "Potpourri", "Artificial Plants"],
    "miscellaneous": ["Greeting Cards", "Gift Wrap", "Ribbons", "Balloons", "Stickers", "Confetti", "Party Hats",
                      "Envelopes", "Tags", "Name Plates", "Diya Set", "Festive Tableware", "Plastic Tray", "Serving Bowl",
                      "Invitation Cards", "Party Favor Bags", "Decorative Box", "Gift Tags", "LED Candles", "Plastic Garland"]
},
  "kids products" : {
    "toys": ["Lego Set", "Action Figures", "Dolls", "Stuffed Animals", "Building Blocks", "Puzzle Games",
             "Remote-control Cars", "Train Set", "Toy Kitchen", "Toy Tools", "Mini Figurines", "Playhouse",
             "Toy Vehicles", "Magnetic Tiles", "Robot Toys", "Outdoor Play Set", "Soft Toys", "Animal Figures",
             "Water Toys", "Stacking Toys"],
    "books": ["Story Books", "Fairy Tales", "Comic Books", "Picture Books", "Bedtime Stories", "Educational Books",
              "Activity Books", "Learning Guides", "Children Encyclopedias", "Puzzle Books", "Adventure Books",
              "Mystery Books", "Poetry Books", "Rhyming Books", "Fables", "Classic Tales", "Science Books",
              "History Books", "Mythology Books", "Coloring Books"],
    "stationery": ["Crayons", "Color Pencils", "Markers", "Sketch Pens", "Drawing Books", "Notebooks", "Glue Stick",
                   "Scissors", "Ruler", "Eraser", "Sharpener", "Stencil Set", "Sticker Sheets", "Paints", "Paint Brush Set",
                   "Geometry Set", "Pencil Box", "Pen Set", "Pencil Case", "Sketch Pads"],
    "educational games": ["Memory Games", "Flash Cards", "Math Puzzles", "Word Games", "Science Kits", "Geography Games",
                          "Language Learning Games", "Coding Toys", "STEM Kits", "Quiz Cards", "Logic Puzzles", "Pattern Blocks",
                          "Counting Toys", "Magnetic Letters", "Educational Board Games", "Alphabet Blocks", "Learning Apps",
                          "Electronic Learning Toys", "Puzzle Books", "Shape Sorting Toys"],
    "clothing": ["T-shirts", "Shorts", "Dresses", "Skirts", "Jeans", "Sweaters", "Jackets", "Socks", "Shoes",
                 "Hats", "Caps", "Pyjamas", "Uniform Sets", "Raincoat", "Boots", "Sandals", "Leggings", "Sweatshirts",
                 "Track Pants", "Winter Coat"],
    "outdoor play": ["Bicycles", "Tricycles", "Scooters", "Skateboards", "Jump Rope", "Frisbee", "Ball Games",
                     "Play Tents", "Slide", "Swing", "Sandbox Set", "Sports Kits", "Outdoor Puzzle", "Mini Golf Set",
                     "Kite", "Water Play Set", "Ride-on Toys", "Balance Bike", "Hula Hoop", "Playhouse"],
    "arts & crafts": ["Paints", "Brushes", "Craft Paper", "Glue", "Scissors", "Stickers", "Beads", "Clay", "Craft Kits",
                      "Origami Paper", "Markers", "Color Pencils", "Crayons", "Stamp Set", "Canvas Board", "Glitter",
                      "Foam Sheets", "Pom Poms", "Pipe Cleaners", "Craft Stencils"],
    "electronics": ["Kids Tablet", "Educational Robot", "Learning Laptop", "Interactive Book", "Music Player", "Karaoke Microphone",
                    "Walkie Talkies", "Headphones", "Digital Camera", "Smart Watch", "Electronic Puzzle", "VR Headset",
                    "Electronic Quiz Game", "Remote-control Toy", "Coding Kit", "Handheld Game Console", "Microscope Kit",
                    "Science Lab Kit", "Interactive Globe", "Digital Drawing Pad"],
    "school essentials": ["Backpack", "Lunch Box", "Water Bottle", "Pencil Box", "Notebooks", "Stationery Set",
                          "Geometry Set", "Eraser", "Pencil", "Markers", "Crayons", "Scissors", "Glue Stick", "Ruler",
                          "Textbooks", "Art Supplies", "Binder", "Lunch Bag", "Calculator", "Name Tags"],
    "sports & fitness": ["Football", "Basketball", "Cricket Kit", "Tennis Racket", "Badminton Set", "Table Tennis Kit",
                         "Yoga Mat", "Skipping Rope", "Mini Trampoline", "Sports Shoes", "Goal Post Set", "Soccer Ball",
                         "Gymnastics Kit", "Hockey Stick", "Baseball Glove", "Swim Goggles", "Kickball", "Resistance Bands",
                         "Fitness Tracker", "Cycling Helmet"]
},
     "courses" : {
    "programming": ["Python Programming", "Java Programming", "C++ Programming", "JavaScript", "Ruby on Rails",
                    "Go Programming", "Rust Programming", "Swift Programming", "Kotlin", "PHP Programming",
                    "SQL Programming", "R Programming", "MATLAB", "Perl", "Scala", "C# Programming", "Dart Programming",
                    "TypeScript", "Objective-C", "Assembly Language"],
    "data science": ["Data Science with Python", "Data Analysis with R", "Machine Learning", "Deep Learning",
                     "Statistics", "Data Visualization", "Big Data Analytics", "Data Mining", "Predictive Analytics",
                     "Time Series Analysis", "Data Engineering", "Data Wrangling", "SQL for Data Science", "Excel for Data Analysis",
                     "Power BI", "Tableau", "AI for Data Science", "Text Mining", "Python for Data Analysis", "Data Modelling"],
    "web development": ["HTML", "CSS", "JavaScript", "React.js", "Angular", "Vue.js", "Node.js", "Express.js",
                        "Django", "Flask", "Ruby on Rails", "PHP", "Laravel", "ASP.NET", "Bootstrap", "jQuery",
                        "REST API Development", "GraphQL", "Web Security", "Web Design Principles"],
    "cloud computing": ["AWS Fundamentals", "Microsoft Azure", "Google Cloud Platform", "Cloud Architecture",
                        "DevOps Basics", "Cloud Security", "Docker", "Kubernetes", "Terraform", "Serverless Architecture",
                        "Cloud Monitoring", "Cloud Storage", "Virtualization", "Cloud Networking", "Cloud Certification Prep",
                        "Cloud Automation", "CI/CD Pipeline", "Cloud Migration", "Cloud Governance", "Hybrid Cloud"],
    "cybersecurity": ["Ethical Hacking", "Network Security", "Penetration Testing", "Cybersecurity Fundamentals",
                      "Cryptography", "Digital Forensics", "Information Security", "Security Auditing", "SOC Analyst",
                      "Incident Response", "Malware Analysis", "Cloud Security", "Web Application Security", "Compliance",
                      "Threat Hunting", "Cybersecurity Tools", "Risk Management", "Security Policies", "Phishing Awareness", "VPN Configuration"],
    "digital marketing": ["SEO", "Social Media Marketing", "Content Marketing", "Email Marketing", "PPC Advertising",
                          "Google Ads", "Facebook Ads", "Instagram Marketing", "LinkedIn Marketing", "Marketing Analytics",
                          "Affiliate Marketing", "Influencer Marketing", "YouTube Marketing", "Marketing Automation",
                          "Brand Management", "Online Advertising", "Conversion Rate Optimization", "Marketing Strategy",
                          "Campaign Management", "E-commerce Marketing"],
    "graphic design": ["Adobe Photoshop", "Adobe Illustrator", "Canva", "InDesign", "CorelDRAW", "Figma",
                       "Sketch", "UX/UI Design", "Motion Graphics", "Video Editing", "Logo Design", "Branding",
                       "Typography", "Color Theory", "Infographic Design", "Poster Design", "Web Design",
                       "Packaging Design", "Print Design", "Illustration"],
    "business analytics": ["Business Analytics", "Financial Analytics", "Operations Analytics", "HR Analytics",
                           "Supply Chain Analytics", "Marketing Analytics", "Data Analytics for Business", "Excel for Analytics",
                           "Tableau for Analytics", "Power BI for Analytics", "Predictive Analytics", "Dashboard Design",
                           "SQL for Analytics", "Python for Analytics", "R for Analytics", "Statistical Analysis",
                           "Decision Modeling", "Risk Analysis", "Performance Metrics", "Forecasting"],
    "soft skills": ["Communication Skills", "Presentation Skills", "Time Management", "Leadership Skills", "Teamwork",
                    "Conflict Management", "Negotiation Skills", "Problem Solving", "Critical Thinking", "Emotional Intelligence",
                    "Public Speaking", "Decision Making", "Networking Skills", "Stress Management", "Adaptability",
                    "Creativity", "Collaboration", "Motivation", "Interpersonal Skills", "Self-Discipline"],
    "certifications": ["AWS Certification", "Azure Certification", "Google Cloud Certification", "PMP",
                       "Six Sigma", "ITIL", "CompTIA Security+", "Certified Ethical Hacker", "Cisco Certification",
                       "Lean Management", "Scrum Master", "Agile Certification", "Certified Data Analyst", "Salesforce",
                       "Oracle Certification", "TOGAF", "Google Analytics", "HubSpot Certification", "Facebook Blueprint",
                       "Microsoft Office Specialist"]
},
    "career" : {
    "resume": ["Resume Optimization", "Professional Templates", "ATS Friendly Resume", "Skill-based Resume",
               "Chronological Resume", "Functional Resume", "Hybrid Resume", "Portfolio Resume", "Infographic Resume",
               "Cover Letter Tips", "Resume Proofreading", "Resume Review Services", "Resume Keywords", "One-page Resume",
               "Two-page Resume", "Resume Layout Tips", "Creative Resume", "LinkedIn Resume", "Career Change Resume", "Internship Resume"],
    "interview": ["Mock Interviews", "Interview Preparation", "Behavioral Questions", "Technical Interviews",
                  "Panel Interviews", "Group Discussions", "Phone Interviews", "HR Round", "Soft Skills Preparation",
                  "STAR Method Practice", "Case Study Interviews", "Role Play Practice", "Presentation Skills",
                  "Interview Etiquette", "Body Language Tips", "Confidence Building", "Answer Structuring",
                  "Salary Negotiation Tips", "Follow-up Emails", "Interview Feedback Review"],
    "career counseling": ["Career Path Guidance", "Job Role Exploration", "Skill Gap Analysis", "Industry Trends",
                          "Career Roadmap Planning", "Work-life Balance Advice", "Job Search Strategies", "Mentorship",
                          "Professional Networking", "Goal Setting", "Self-assessment Tests", "SWOT Analysis", "Strengths Mapping",
                          "Personality Assessment", "Interest Inventory", "Long-term Career Planning", "Freelancing Advice",
                          "Portfolio Development", "Internship Guidance", "Career Transition Planning"],
    "skills": ["Communication Skills", "Leadership Skills", "Time Management", "Problem Solving", "Critical Thinking",
               "Decision Making", "Negotiation Skills", "Teamwork & Collaboration", "Presentation Skills", "Adaptability",
               "Emotional Intelligence", "Creativity", "Conflict Management", "Networking", "Self-discipline", "Public Speaking",
               "Stress Management", "Analytical Thinking", "Persuasion Skills", "Coaching & Mentoring"],
    "job search": ["Job Portals", "LinkedIn Profile Optimization", "Company Research", "Job Alerts", "Networking Events",
                   "Industry Connections", "Career Fairs", "Job Applications", "Recruiter Outreach", "Cover Letter Writing",
                   "Portfolio Building", "Freelancing Platforms", "Startup Opportunities", "Internships", "Remote Jobs",
                   "Job Search Apps", "Skill-based Job Matching", "Company Referrals", "Online Job Boards", "Recruitment Agencies"],
    "entrepreneurship": ["Startup Ideas", "Business Plan", "Funding Strategies", "Market Research", "Business Model",
                         "Pitch Deck Creation", "Lean Startup Methodology", "Customer Validation", "Brand Development",
                         "Marketing Strategies", "Financial Planning", "Legal Aspects", "Networking for Entrepreneurs",
                         "Product Development", "Sales Strategies", "Operations Management", "Growth Hacking", "Mentorship",
                         "Pitching to Investors", "Scaling Business"],
    "freelancing": ["Freelance Platforms", "Profile Optimization", "Portfolio Development", "Client Acquisition",
                    "Pricing Strategy", "Project Management", "Time Management", "Communication Skills", "Contracts & Agreements",
                    "Invoice Management", "Proposal Writing", "Negotiation Skills", "Marketing Yourself", "Social Media",
                    "Networking for Freelancers", "Skill Enhancement", "Portfolio Website", "Feedback & Reviews", "Remote Work Tools", "Client Retention"],
    "certifications": ["AWS Certification", "Azure Certification", "Google Cloud Certification", "PMP", "Six Sigma",
                       "ITIL", "CompTIA Security+", "Certified Ethical Hacker", "Cisco Certification", "Lean Management",
                       "Scrum Master", "Agile Certification", "Certified Data Analyst", "Salesforce", "Oracle Certification",
                       "TOGAF", "Google Analytics", "HubSpot Certification", "Facebook Blueprint", "Microsoft Office Specialist"],
    "career change": ["Skill Assessment", "Industry Research", "Upskilling Courses", "Networking", "Resume Update",
                      "Interview Preparation", "Portfolio Development", "Mentorship", "Job Shadowing", "Internship Programs",
                      "Self-employment Options", "Freelancing", "Professional Coaching", "Volunteer Opportunities", "Certifications",
                      "Workshops", "Career Fairs", "Informational Interviews", "Mentor Matching", "Professional Associations"],
    "work-life balance": ["Time Management", "Prioritization Techniques", "Delegation Skills", "Stress Management",
                          "Mindfulness Practices", "Exercise Routine", "Healthy Eating", "Sleep Optimization", "Hobbies & Leisure",
                          "Digital Detox", "Work-from-Home Strategies", "Flexible Scheduling", "Boundary Setting", "Family Time",
                          "Goal Setting", "Self-care Activities", "Mental Health Resources", "Relaxation Techniques", "Planning Tools", "Energy Management"]
},
    "ideas" : {
    "startup": ["Tech Startup Ideas", "E-commerce Ideas", "Social Impact Startups", "Food & Beverage Startups",
                "Healthcare Startups", "EdTech Startups", "Green Startups", "AI Startups", "Mobile App Startups",
                "SaaS Ideas", "FinTech Ideas", "IoT Ideas", "Gaming Startups", "Travel Startups", "Lifestyle Startups",
                "Media & Entertainment Ideas", "Retail Startups", "Fashion Startups", "Blockchain Startups", "Subscription Box Ideas"],
    "business": ["Consulting Business", "Event Planning Business", "Dropshipping Business", "Digital Marketing Agency",
                 "Freelance Agency", "Blogging Business", "Affiliate Marketing", "Tutoring Service", "Printing Business",
                 "Online Store", "Photography Business", "Food Truck", "Fitness Business", "Handmade Crafts", "Tourism Business",
                 "Coaching Business", "Subscription Services", "Pet Services", "Mobile Services", "Real Estate Business"],
    "content": ["YouTube Video Ideas", "Blog Post Ideas", "Instagram Post Ideas", "Podcast Ideas", "TikTok Video Ideas",
                "LinkedIn Content Ideas", "Facebook Content Ideas", "Twitter Thread Ideas", "Newsletter Ideas", "Infographic Ideas",
                "E-book Ideas", "Webinar Ideas", "Slide Deck Ideas", "Tutorial Series Ideas", "Online Course Content Ideas",
                "Case Study Ideas", "Interview Series Ideas", "Review Content Ideas", "DIY Video Ideas", "Behind-the-Scenes Content"],
    "social media": ["Instagram Campaign", "Facebook Post Series", "Twitter Engagement Campaign", "LinkedIn Content Plan",
                     "YouTube Channel Series", "TikTok Challenges", "Pinterest Boards", "Social Media Polls", "Influencer Collaboration",
                     "Live Streaming Ideas", "Viral Content Ideas", "UGC Campaign", "Brand Storytelling", "Hashtag Campaign",
                     "Giveaway Ideas", "Event Promotion Ideas", "Content Calendar", "Story Highlights", "Reels Series", "Community Engagement"],
    "projects": ["Science Projects", "DIY Projects", "Engineering Projects", "School Projects", "College Projects",
                 "Art Projects", "Coding Projects", "Business Projects", "Social Projects", "Research Projects",
                 "Tech Projects", "Marketing Projects", "Creative Projects", "Design Projects", "Environmental Projects",
                 "Community Projects", "Photography Projects", "Writing Projects", "Innovation Projects", "Startup Projects"],
    "marketing": ["Campaign Ideas", "Product Launch Ideas", "Content Marketing Ideas", "Email Marketing Ideas",
                  "Social Media Ads", "Influencer Marketing Ideas", "SEO Strategies", "Referral Program Ideas", "Brand Positioning",
                  "PR Strategies", "Loyalty Programs", "Event Marketing Ideas", "Promotional Ideas", "Video Marketing Ideas",
                  "Podcast Marketing Ideas", "Affiliate Marketing Ideas", "Product Packaging Ideas", "Customer Engagement Ideas",
                  "Seasonal Campaign Ideas", "Discount Strategies"],
    "event": ["Wedding Event Ideas", "Birthday Party Ideas", "Corporate Event Ideas", "Festival Event Ideas",
              "Charity Event Ideas", "Product Launch Event Ideas", "Workshop Event Ideas", "Networking Event Ideas",
              "Community Event Ideas", "Sports Event Ideas", "Virtual Event Ideas", "Hybrid Event Ideas", "Team Building Ideas",
              "Conference Ideas", "Seminar Ideas", "Award Ceremony Ideas", "Concert Event Ideas", "Art Exhibition Ideas",
              "Food Festival Ideas", "Themed Party Ideas"],
    "gift": ["Birthday Gifts", "Anniversary Gifts", "Housewarming Gifts", "Thank You Gifts", "Get Well Soon Gifts",
             "Farewell Gifts", "Congratulations Gifts", "Valentine's Gifts", "Mother's Day Gifts", "Father's Day Gifts",
             "Christmas Gifts", "New Year Gifts", "Graduation Gifts", "Friendship Gifts", "Corporate Gifts", "Diwali Gifts",
             "Eid Gifts", "Wedding Gifts", "Baby Shower Gifts", "Retirement Gifts"],
    "DIY": ["Home Decor DIY", "Gift DIY", "Clothing DIY", "Jewelry DIY", "Party DIY", "Art & Craft DIY", "School Project DIY",
            "Tech DIY", "Garden DIY", "Furniture DIY", "Wall Art DIY", "Candle Making", "Scrapbooking", "Painting DIY",
            "Recycling DIY", "Card Making DIY", "Fabric Painting DIY", "Photography DIY", "Decorative DIY", "Woodworking DIY"],
    "fundraising": ["Crowdfunding Ideas", "Charity Fundraising", "School Fundraising", "Community Fundraising", "Online Fundraising",
                    "Event Fundraising", "Sports Fundraising", "Corporate Fundraising", "Donation Drives", "Nonprofit Fundraising",
                    "Art Sale Fundraising", "Food Sale Fundraising", "Auction Fundraising", "Raffle Fundraising", "Concert Fundraising",
                    "Social Media Fundraising", "Marathon Fundraising", "Gaming Fundraising", "DIY Fundraising", "Volunteer-driven Fundraising"]
},
    "party organizing" : {
    "theme": ["Masquerade", "Hollywood", "Beach Party", "Retro", "Black & White", "Carnival", "Hollywood Glam",
              "Disney", "Superhero", "Fairy Tale", "Hawaiian", "Christmas", "Halloween", "80s Theme", "Garden Party",
              "Masquerade Ball", "Casino Night", "Movie Night", "Pool Party", "Birthday Bash"],
    "invitations": ["Printed Cards", "Digital Invitations", "E-invites", "Photo Invitations", "Video Invitations",
                    "Custom Illustrations", "Themed Invitations", "Handmade Invitations", "Social Media Invites", "Interactive Invitations",
                    "Popup Cards", "Laser Cut Invitations", "Foil Invitations", "Calligraphy Invitations", "Bookmark Invitations",
                    "Map Card Invitations", "Gift Card Invitations", "Puzzle Invitations", "Confetti Invitations", "Scroll Invitations"],
    "venue decoration": ["Balloon Decoration", "Streamers", "Themed Props", "Photo Booth", "Lighting Setup", "Banners",
                         "Flowers", "Table Setup", "Chair Covers", "Ceiling Decor", "Backdrop", "Centerpieces", "Ribbons",
                         "Tablecloths", "Candles", "Lanterns", "Garlands", "Fairy Lights", "Sign Boards", "Entrance Decor"],
    "cake": ["Chocolate Cake", "Vanilla Cake", "Red Velvet Cake", "Black Forest Cake", "Cheesecake", "Fondant Cake",
             "Cupcakes", "Layered Cake", "Custom Design Cake", "Fruit Cake", "Carrot Cake", "Buttercream Cake", "Ice Cream Cake",
             "Theme Cake", "Wedding Cake", "Anniversary Cake", "Birthday Cake", "Mini Cakes", "Sponge Cake", "Drip Cake"],
    "catering": ["Buffet", "Finger Food", "Appetizers", "Desserts", "Snacks", "Beverages", "Cocktails", "Mocktails",
                 "Theme-based Menu", "Salads", "Pasta", "Pizza", "BBQ", "Food Trucks", "Kids Menu", "Vegan Menu",
                 "Gluten-Free Options", "Sushi Bar", "Ice Cream Station", "Chocolate Fountain"],
    "music": ["DJ", "Live Band", "Playlist Curation", "Karaoke", "Acoustic Music", "Instrumental Background", "Dance Music",
              "Theme Music", "Sound Effects", "Wedding Songs", "Birthday Songs", "Party Hits", "Classical Music", "Pop Music",
              "Rock Music", "Jazz", "Folk Music", "Reggae", "Electronic Music", "Live Performance"],
    "games & activities": ["Treasure Hunt", "Musical Chairs", "Charades", "Board Games", "Outdoor Games", "Quiz Competition",
                           "Relay Race", "Dance Competition", "Photo Contest", "Karaoke Contest", "Minute to Win It", "Scavenger Hunt",
                           "Talent Show", "Balloon Pop Game", "Guess the Song", "Ring Toss", "Dart Game", "Pin the Tail", "Obstacle Course", "Spin the Wheel"],
    "return gifts": ["Gift Bags", "Candies", "Toys", "Stationery", "Mini Plants", "Keychains", "Personalized Gifts", "Chocolate Boxes",
                     "Mugs", "Photo Frames", "Mini Notebooks", "Handmade Crafts", "Bracelets", "Bookmarks", "Socks", "Caps", "Stress Balls",
                     "Puzzle Games", "Snack Packs", "Eco-friendly Gifts"],
    "table arrangement": ["Tablecloths", "Centerpieces", "Napkin Folding", "Cutlery Placement", "Glassware Setup", "Plates Arrangement",
                          "Seating Plan Cards", "Candles", "Flower Vases", "Theme Props", "Table Numbers", "Chair Sashes", "Table Runner",
                          "Place Mats", "Buffet Setup", "Dessert Table", "Beverage Station", "Cake Table Setup", "Food Labels", "Menu Cards"],
    "cleanup planning": ["Waste Bins", "Recycling", "Trash Bags", "Cleaning Supplies", "Post-party Cleanup", "Team Assignment",
                         "Dishwashing Plan", "Decoration Dismantle", "Lost & Found Items", "Storage Plan", "Leftover Food Distribution",
                         "Donation Plan", "Rental Return Plan", "Furniture Arrangement", "Sanitization", "Laundry", "Sweeping & Mopping",
                         "Vacuum Cleaning", "Final Inspection", "Checklist"]
},

}


latest = df.iloc[-1]

# Extract data with proper error handling
try:
    category = str(latest.get('Select Category?', 'Not found')).strip()
    description = str(latest.get('Describe for what you need recommendation?', 'Not found')).strip()
    budget = str(latest.get('Budget?', 'Not provided')).strip()
except Exception as e:
    st.error(f"Error extracting data: {e}")
    st.info(f"Available columns: {df.columns.tolist()}")
    st.stop()


def recommendation_agent(category, description, budget=None):

    category_key = category.strip().lower()
    desc_lower = description.lower()

    if category_key not in recommendations:
        return ["Category not found"]

    matched_items = []
    category_data = recommendations[category_key]

    if isinstance(category_data, dict):
        for subcat, items in category_data.items():
            if subcat.lower() in desc_lower:
                matched_items.extend(items)

        if not matched_items:
            for items in category_data.values():
                matched_items.extend(items)

    elif isinstance(category_data, list):
        matched_items = category_data

    return matched_items[:20]


# ---------------- UI ----------------

st.title("AI Recommendation System")

st.subheader("Latest Google Form Response")

st.write({
    "Category": category,
    "Description": description,
    "Budget": budget
})

if category == "Not found" or description == "Not found":
    st.warning("⚠️ No valid data found in the Google Sheet. Please fill out the form first.")
else:
    results = recommendation_agent(
        category,
        description,
        budget
    )

    st.subheader("Recommendations")

    if results:
        for i, item in enumerate(results, start=1):
            st.write(f"{i}. {item}")
    else:
        st.info("No recommendations found for this category.")
    
